In [2]:
import torch

#从list创建
torch.tensor([1, 2]), torch.tensor([[1, 2], [3, 4]])

(tensor([1, 2]),
 tensor([[1, 2],
         [3, 4]]))

In [3]:
import numpy as np

#从numpy创建
torch.from_numpy(np.array([1, 2]))

tensor([1, 2], dtype=torch.int32)

In [4]:
#全1填充
print(torch.ones(2, 3))

#全0填充
print(torch.zeros(2, 3))

#full填充
print(torch.full([2, 3], 7))

#对角矩阵
print(torch.eye(3, 3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[7, 7, 7],
        [7, 7, 7]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [5]:
#创建但不初始化
print(torch.empty(2, 3))

#标准正态分布
print(torch.randn(2, 3))

#0-1均匀分布
print(torch.rand(2, 3))

#1-9的整数均匀分布
print(torch.randint(1, 10, [2, 3]))

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 5.9694e-39]])
tensor([[ 0.8910, -0.2646, -1.2019],
        [ 0.8155, -0.8255,  0.1633]])
tensor([[0.1552, 0.6845, 0.3138],
        [0.0329, 0.3883, 0.3087]])
tensor([[9, 5, 2],
        [6, 9, 4]])


In [6]:
#自增数列,0到9,步长是2
print(torch.arange(0, 10, 2))

#等差数列,0到10,4个数
print(torch.linspace(0, 10, 4))

tensor([0, 2, 4, 6, 8])
tensor([ 0.0000,  3.3333,  6.6667, 10.0000])


In [6]:
#指定类型的创建
torch.FloatTensor([1, 2]), torch.LongTensor([1, 2])

(tensor([1., 2.]), tensor([1, 2]))

In [7]:
#获取数据类型
torch.randn(2, 3).dtype

torch.float32

In [8]:
#转换数据类型
torch.randn(2, 3).to(torch.float64).dtype

torch.float64