In [2]:
import torch

#view,reshape维度变换

#4张图片,单通道,28*28像素
a = torch.randn(4, 1, 28, 28)
print(a.shape)

#转换为4,784维度,相当于打平了
print(a.reshape(4, 784).shape)

#转换为4,28,28维度,相当于重新展开
print((a.reshape(4, 784)).reshape(4, 28, 28).shape)

#view的用法和reshape是完全一样的')
print(a.view(4, 784).shape)

torch.Size([4, 1, 28, 28])
torch.Size([4, 784])
torch.Size([4, 28, 28])
torch.Size([4, 784])


In [5]:
#unsqueeze插入维度

#2*2的tensor
a = torch.randn(2, 2)
print(a.shape)
print(a)

b = torch.randn(2, 2, 2)
print(b)
#插入维度在第0维
print(a.unsqueeze(0).shape)
print(a.unsqueeze(0))


#插入维度在倒数第1维
print(a.unsqueeze(-1).shape)
print(a.unsqueeze(-1))

torch.Size([2, 2])
tensor([[ 1.5198,  1.3019],
        [ 0.0051, -0.5346]])
tensor([[[-1.6404, -0.5800],
         [-1.0957,  1.4132]],

        [[ 0.1342,  0.4318],
         [ 1.1067,  1.6023]]])
torch.Size([1, 2, 2])
tensor([[[ 1.5198,  1.3019],
         [ 0.0051, -0.5346]]])
torch.Size([2, 2, 1])
tensor([[[ 1.5198],
         [ 1.3019]],

        [[ 0.0051],
         [-0.5346]]])


In [6]:
#squeeze删除维度,只能删除为1的维度

#1*2*2*1的tensor
a = torch.randn(1, 2, 2, 1)
print(a.shape)

#删除第0维
print(a.squeeze(0).shape)

#删除倒数第1维
print(a.squeeze(-1).shape)

#删除所有为1的维度
print(a.squeeze().shape)

torch.Size([1, 2, 2, 1])
torch.Size([2, 2, 1])
torch.Size([1, 2, 2])
torch.Size([2, 2])


In [4]:
#repeat复制维度

#分别复制2次和3次 第一个维度重复2次,第二个维度重复3次
print(torch.randn(2, 2).repeat(2, 3).shape)

torch.Size([4, 6])


In [5]:
#维度交换

#t转置,只能操作2维tensor
print(torch.randn(1, 2).t().shape)

#transpose维度交换,指定要转换的维度,只能两两交换
print(torch.randn(1, 2, 3).transpose(0, 1).shape)

#permute维度交换,输入维度的顺序
print(torch.rand(1, 2, 3).permute(2, 1, 0).shape)

torch.Size([2, 1])
torch.Size([2, 1, 3])
torch.Size([3, 2, 1])
